version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-azizi-amp-db:
    container_name: §§INSTANCE-azizi-amp-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    image: mariadb
    environment:
      - MYSQL_DATABASE=§§MYSQL_DATABASE
      - MYSQL_USER=§§MYSQL_USER
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=admin
    depends_on:
      - §§INSTANCE-azizi-amp-data
    volumes_from: 
      - §§INSTANCE-azizi-amp-data

  §§INSTANCE-azizi-amp-web:
    image: soloincc/azizi_amp
    container_name: §§INSTANCE-azizi-amp-web
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8089"
    networks:
      - bibbox-default-network
    links:
      - "§§INSTANCE-azizi-amp-db:azizi-amp-db"
    environment:
      - MYSQL_DATABASE=§§MYSQL_DATABASE
      - MYSQL_USER=§§MYSQL_USER
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
      - MYSQL_HOST=azizi-amp-db
      - MYSQL_PORT=3306
      
    ports:
      - "§§PORT:8089"
    depends_on:
      - §§INSTANCE-azizi-amp-db
      - §§INSTANCE-azizi-amp-data
    volumes_from: 
      - §§INSTANCE-azizi-amp-data

  §§INSTANCE-azizi-amp-data:
    image: busybox
    container_name: §§INSTANCE-azizi-amp-data
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./azizi-amp:/opt/azizi-amp