version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  azizi-amp-db:
    container_name: azizi-amp-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=b3africa
      - MYSQL_USER=b3africa
      - MYSQL_PASSWORD=admin
    depends_on:
      - azizi-amp-data
    volumes_from: 
      - azizi-amp-data

  azizi-amp-web:
    # build: .
    image: soloincc/azizi_amp
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8089"
    networks:
      - bibbox-default-network
    links:
      - "azizi-amp-db:azizi-amp-db"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=b3africa
      - MYSQL_USER=b3africa
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=azizi-amp-db
      - MYSQL_PORT=3306
    ports:
      - "8089:8089"
    depends_on:
      - azizi-amp-db
      - azizi-amp-data
    volumes_from: 
      - azizi-amp-data

  azizi-amp-data:
    image: busybox
    container_name: azizi-amp-data
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./azizi-amp:/opt/azizi-amp